### ISSUE TITLE
Deleted products are not properly handled

### ISSUE THREAD

**Issue by mintplugins** [easydigitaldownloads/edd-clickbank-gateway#3]
This extension prevents you from using the same ClickBank item number for multiple products. 

The way it does this is by hooking to the "save_post" method, and adding the clickbank item number to an array. That array is checked when saving any new clickbank products. 

However, if you delete a product from your EDD Store, it is not removed from that array. Therefore, you can no longer use that ClickBank ID anymore. 

To fix this, we'll need to actually query all the payments which have clickbank meta and compare each one. This will make sure it is always accurate.

**Comment by mintplugins** [comment]
After digging in a bit further, I believe this will require an upgrade routine to fix.

**Comment by pippinsplugins** [comment]
There's another way to solve this without requiring an upgrade routine.

1. During save_post look up the saved items to see if the item being saved is in the array
2. If it is in the array, query for other Downloads with a clickbank item saved.
3. If another download product is found with the same item, disallow. If no published download is found, allow the item to be saved, replacing the other.

**Comment by mintplugins** [comment]
The difficult part is that you can't query based on post meta (because there isn't any). 

But I suppose you could query using the "p" parameter and pass all the post IDs from the array of clickbank posts.

**Comment by pippinsplugins** [comment]
Yep that should work!

**Comment by mintplugins** [comment]
Waiting for confirmation from customer here:
https://secure.helpscout.net/conversation/479918882/71895?folderId=180504

**Comment by mintplugins** [comment]
@pippinsplugins I'm having an issue with running the WP_Query. While it solves the problem it is intended to, it creates another one in that the query is not being properly reset afterwards. 

This means that, when creating a new product, the slug/permalink becomes the exact same as the slug/permalink for the list item in the query. 

I have attempted to use both wp_reset_query and wp_reset_postdata but neither have fixed it. Any ideas? 

![slug-issue](https://user-images.githubusercontent.com/1638128/33770568-1fc9406a-dbfc-11e7-8051-334490719c41.jpg)

**Comment by mintplugins** [comment]
I took a different approach. Instead of running a query, I am now looping through the Clickbank post ids and instantiating an EDD_Download object. If the Id of that object is `0`, we know the post does not exist so we can remove it that way. This way there's no need to run any query. It is working better in my tests.

**Comment by pippinsplugins** [comment]
@mintplugins PR looks good to me!
